management:
  endpoints:
    web:
      # override endpoint name for health check: `/health` => `/status`
      path-mapping:
        health: /status
# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    platform: h2
    url: jdbc:h2:file:~/batch
    username: sa
    password: